name: CustomAttributePotion
version: ${version}
main: ru.edenor.customAttributePotion.CustomAttributePotion
api-version: '1.21.7'
author: Totilak
contributors: [WesOrangePower]
description: "Плагин для Minecraft, который добавляет настраиваемые зелья атрибутов."
folia-supported: true
permissions:
  cap.give:
    description: Права для выдачи зелий
  cap.use:
    description: Права для использований плагина, как игрок (cap check)
  cap.list:
    description: Права для просмотра списка зелий
